#!/usr/bin/python3
# Copyright 2021 Alexander Wilhelmi
# This file is part of getcalendaroverview.
# 
# getcalendaroverview is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# getcalendaroverview is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with getcalendaroverview.  If not, see <http://www.gnu.org/licenses/>.
# 
# Diese Datei ist Teil von getcalendaroverview.
# 
# getcalendaroverview ist Freie Software: Sie können es unter den Bedingungen
# der GNU General Public License, wie von der Free Software Foundation,
# Version 3 der Lizenz oder (nach Ihrer Wahl) jeder neueren
# veröffentlichten Version, weiter verteilen und/oder modifizieren.
# 
# getcalendaroverview wird in der Hoffnung, dass es nützlich sein wird, aber
# OHNE JEDE GEWÄHRLEISTUNG, bereitgestellt; sogar ohne die implizite
# Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
# Siehe die GNU General Public License für weitere Details.
# 
# Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
# Programm erhalten haben. Wenn nicht, siehe <https://www.gnu.org/licenses/>.
import datetime
from os import environ as env
from os.path import sep as psep
from subprocess import check_output
from os.path import exists
from os import listdir
from os.path import dirname
from os.path import basename
from re import match
from argparse import ArgumentParser

DIARY_PATH = env['HOME']+'/PIM/diary'

def parse_args():
    ap=ArgumentParser("prints count days of the diary starting at today")
    ap.add_argument("days",nargs='?',type=int,default=2)
    args=ap.parse_args()
    return args


def main():
    for i in range(args.days):
        d=str(datetime.datetime.fromordinal(datetime.date.today().toordinal() + i ).date()).split('-')
        year=d[0]
        month=int(d[1])
        day=int(d[2])
        date = [ year , month , day]
        date = [ str(d) for d in date]
        datepath = psep.join(date)
        filepath = DIARY_PATH + psep + datepath + '.md'
        if exists(filepath):
            with open(filepath) as f:
                ldp=len(datepath)
                print(f"{datepath} [")
                print("="*ldp)
                lines=f.read().split(psep)
                for line in lines:
                    print(" "*(ldp+2)+line)
        dn=dirname(filepath)
        bn=basename(filepath)
        dirlist=listdir(dn)
        ldn=len(dn)
        for thing in dirlist:
            if match(bn[:-3]+'.+[.]md',thing):
                header = f"warning: extra file: {thing} ["
                lh=len(header)
                print(header)
                with open(dn+psep+thing) as f:
                    lines=f.read().split(psep)
                    for line in lines:
                        print(" "*lh+line)
                print((lh-1)*" "+"]")
        print(ldp*" "+" ]")

if __name__=="__main__":
    args=parse_args()
    main()
